### 회원가입 API
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
    "uid": "test3Uid",
    "password" : "test3Password",
    "name" : "test3Name"
}

### 로그인 API
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "uid": "test3Uid",
  "password": "test3Password"
}

